import unittest
import asyncio
import os
import httpx
from datetime import datetime, timezone
from app.main import app
from app.core.config import settings
from app.db.redis import get_redis
from app.db.postgres import db_manager

def get_test_secret(name: str) -> str:
    # Resolves secrets in local directory or mounted path
    paths = [
        f"secrets/{name}.txt",
        f"../secrets/{name}.txt",
        f"/run/secrets/{name}"
    ]
    for p in paths:
        if os.path.exists(p):
            with open(p, "r") as f:
                return f.read().strip()
    return "default_password"

class TestAuthRoutes(unittest.TestCase):
    def setUp(self):
        # Read passwords generated by setup_security.sh
        self.operator_password = get_test_secret("operator_password")
        self.supervisor_password = get_test_secret("supervisor_password")
        
        # Point the app's get_secret to local secrets folder
        os.environ["OPERATOR_PASSWORD_FILE"] = os.path.abspath("secrets/operator_password.txt")
        os.environ["SUPERVISOR_PASSWORD_FILE"] = os.path.abspath("secrets/supervisor_password.txt")
        os.environ["POSTGRES_PASSWORD_FILE"] = os.path.abspath("secrets/postgres_password.txt")

    def run_async(self, coro):
        return asyncio.run(coro)

    async def run_test_with_fresh_connections(self, test_coro):
        """
        Helper method to run tests under a fresh event loop and establish
         Postgres & Redis pools bound specifically to that event loop.
        """
        # 1. Postgres connection pool initialization for this loop
        if db_manager.pool:
            await db_manager.disconnect()
        await db_manager.connect()
        
        # 2. Redis connection pool initialization for this loop
        from app.db.redis import redis_manager
        from redis.asyncio import Redis, ConnectionPool
        try:
            await redis_manager.close()
        except Exception:
            pass
        redis_manager.pool = ConnectionPool.from_url(settings.redis_connection_url, decode_responses=True)
        redis_manager.client = Redis(connection_pool=redis_manager.pool)
        
        # 3. Seed users if needed (via superuser connection)
        from app.main import seed_users
        await seed_users()
        
        try:
            # Run the actual test coroutine
            await test_coro()
        finally:
            # 4. Clean up connection pools
            await db_manager.disconnect()
            try:
                await redis_manager.close()
            except Exception:
                pass

    def test_login_success_and_failure(self):
        """
        Test auth login route with correct and incorrect credentials.
        """
        async def run_test():
            async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://test") as client:
                # 1. Incorrect credentials
                resp = await client.post("/auth/login", json={
                    "username": "operator",
                    "password": "wrong_password"
                })
                self.assertEqual(resp.status_code, 401)
                
                # 2. Correct credentials (operator)
                resp = await client.post("/auth/login", json={
                    "username": "operator",
                    "password": self.operator_password
                })
                self.assertEqual(resp.status_code, 200)
                data = resp.json()
                self.assertIn("access_token", data)
                self.assertIn("refresh_token", data)
                self.assertEqual(data["token_type"], "bearer")

        self.run_async(self.run_test_with_fresh_connections(run_test))

    def test_rbac_dashboard_and_incidents(self):
        """
        Verify RBAC enforcement:
        - Operators can read dashboard but cannot acknowledge/resolve incidents.
        - Supervisors can read dashboard and can acknowledge/resolve incidents.
        """
        async def run_test():
            async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://test") as client:
                # 1. Login as operator
                op_login = await client.post("/auth/login", json={
                    "username": "operator",
                    "password": self.operator_password
                })
                op_token = op_login.json()["access_token"]
                op_headers = {"Authorization": f"Bearer {op_token}"}
                
                # 2. Login as supervisor
                sup_login = await client.post("/auth/login", json={
                    "username": "supervisor",
                    "password": self.supervisor_password
                })
                sup_token = sup_login.json()["access_token"]
                sup_headers = {"Authorization": f"Bearer {sup_token}"}
                
                # 3. Access dashboard as operator - should succeed
                resp = await client.get("/dashboard/status", headers=op_headers)
                self.assertEqual(resp.status_code, 200)
                
                # 4. Attempt to acknowledge incident as operator - should fail (403)
                resp = await client.post("/incidents/L2_WashroomA/acknowledge", headers=op_headers)
                self.assertEqual(resp.status_code, 403)
                
                # 5. Access dashboard as supervisor - should succeed
                resp = await client.get("/dashboard/status", headers=sup_headers)
                self.assertEqual(resp.status_code, 200)
                
                # 6. Acknowledge incident as supervisor - should succeed if incident exists
                # We seed the washroom state in Redis first to simulate an active incident
                redis = await get_redis()
                await redis.set("state:washroom:L2_WashroomA", "ACTIVE_INCIDENT")
                
                resp = await client.post("/incidents/L2_WashroomA/acknowledge", headers=sup_headers)
                self.assertEqual(resp.status_code, 200)
                
                # Verify state is updated in Redis to ACKNOWLEDGED
                val_bytes = await redis.get("state:washroom:L2_WashroomA")
                val = val_bytes.decode("utf-8") if isinstance(val_bytes, bytes) else val_bytes
                self.assertEqual(val, "ACKNOWLEDGED")

                # 7. Resolve incident as supervisor - should succeed
                resp = await client.post("/incidents/L2_WashroomA/resolve", headers=sup_headers)
                self.assertEqual(resp.status_code, 200)

                # Verify state is updated in Redis to NORMAL
                val_bytes = await redis.get("state:washroom:L2_WashroomA")
                val = val_bytes.decode("utf-8") if isinstance(val_bytes, bytes) else val_bytes
                self.assertEqual(val, "NORMAL")

        self.run_async(self.run_test_with_fresh_connections(run_test))

    def test_refresh_token_rotation_and_reuse_revocation(self):
        """
        Verify that:
        - Refresh token rotation issues a new token pair and revokes the old one.
        - Refresh token reuse detection triggers immediate revocation of all sessions for that user.
        """
        async def run_test():
            async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://test") as client:
                # 1. Login to get initial refresh token
                login_resp = await client.post("/auth/login", json={
                    "username": "operator",
                    "password": self.operator_password
                })
                data = login_resp.json()
                initial_access = data["access_token"]
                initial_refresh = data["refresh_token"]
                
                # 2. First refresh rotation call (legitimate)
                refresh_resp_1 = await client.post("/auth/refresh", json={
                    "refresh_token": initial_refresh
                })
                self.assertEqual(refresh_resp_1.status_code, 200)
                data_1 = refresh_resp_1.json()
                new_access_1 = data_1["access_token"]
                new_refresh_1 = data_1["refresh_token"]
                
                # Ensure new access token works
                dashboard_resp = await client.get("/dashboard/status", headers={"Authorization": f"Bearer {new_access_1}"})
                self.assertEqual(dashboard_resp.status_code, 200)
                
                # 3. Second refresh rotation call using the SAME old refresh token (REUSE DETECTED!)
                refresh_resp_2 = await client.post("/auth/refresh", json={
                    "refresh_token": initial_refresh
                })
                self.assertEqual(refresh_resp_2.status_code, 401)
                self.assertIn("Token reuse detected", refresh_resp_2.json()["detail"])
                
                # 4. Verify that the refresh token issued in step 2 is now REVOKED
                refresh_revoked_resp = await client.post("/auth/refresh", json={
                    "refresh_token": new_refresh_1
                })
                self.assertEqual(refresh_revoked_resp.status_code, 401)
                self.assertIn("Invalid or expired refresh token", refresh_revoked_resp.json()["detail"])

        self.run_async(self.run_test_with_fresh_connections(run_test))

if __name__ == "__main__":
    unittest.main()
